apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices.fullname" . }}-secrets
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  postgres-auth-password: {{ .Values.secrets.postgres.authPassword | quote }}
  postgres-user-password: {{ .Values.secrets.postgres.userPassword | quote }}
  rabbitmq-username: {{ .Values.secrets.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
