{{- if .Values.userService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
  labels:
    {{- include "userService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "userService.selectorLabels" . | nindent 4 }}
{{- end }}
